# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: st-lsm6dsv16x
      url-base: https://github.com/STMicroelectronics
    - name: personal-repo
      url-base: https://github.com/nicogou/

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: v2.7.0
      import: true
    - name: lsm6dsv16x-pid
      remote: st-lsm6dsv16x
      revision: main
      path: xiao-ble-lsm6dsv16x.git/lib/lsm6dsv16x/lsm6dsv16x-pid
    - name: FIT-SDK
      remote: personal-repo
      revision: main
      path: xiao-ble-lsm6dsv16x.git/lib/fit_sdk/custom_fit_sdk
    - name: zephyr_module_test
      remote: personal-repo
      revision: main
      path: modules/zephyr_test_module
